import About from "@/components/Landing/About";
import Course from "@/components/Landing/Course";
import FAQ from "@/components/Landing/FAQ";
import ForWho from "@/components/Landing/ForWho";
import Guarantee from "@/components/Landing/Guarantee";
import Hero from "@/components/Landing/Hero";
import HowItWorks from "@/components/Landing/HowItWorks";
import Offer from "@/components/Landing/Offer";
import Tired from "@/components/Landing/Tired";
import Perks from "@/components/Landing/Perks";
import Head from "next/head";
import Schedule from "@/components/Landing/Schedule";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Perks />
      <Course />
      <ForWho />
      <HowItWorks />
      <Tired />
      <Schedule />
      <About />
      <Offer />
      <Guarantee />
      <FAQ />
    </>
  );
}
